### ISSUE TITLE
Module import intellisense, and type signatures

### ISSUE THREAD

**Issue by reygoch** [haskelly-dev/Haskelly#11]
Hi, I'd just like to know if you plan on supporting intellisense for module imports and for showing type signatures of functions that pop up on intellisense?

Also, I might join in on the fun in two weeks when my exams are over :D

**Comment by martrik** [comment]
Hi! I think we could integrate the Intero command ":type-at" which provides type information. I'll have a look over the weekend and let you know about my findings.

By the way, we would be very happy if you were interested in helping us with the development of Haskelly :)

**Comment by reygoch** [comment]
@martrik I think I will. I have to work on my graduation project next semester and I'm kind of fed up with atom and emacs at this point :)

**Comment by martrik** [comment]
This should be solved by the Type hover feature.
