### ISSUE TITLE
Files or Stack projects with white spaces in their path not supported

### ISSUE THREAD

**Issue by Kurren123** [haskelly-dev/Haskelly#16]
Hi

When I hover over a type to see the definition it says "loading" no matter how long I wait for. Windows 10 64 bit.

![image](https://cloud.githubusercontent.com/assets/3525980/22618929/00d8cc3c-eae1-11e6-98b2-1d05d974d1ad.png)

**Comment by dpratt71** [comment]
I had the same problem on the same OS. I eventually tracked it down to the fact that I had set the ghci prompt to "λ> " in my .ghci file. Something about the way the encoding is set up when Haskelly attaches to the stdout of ghci causes ghci to error attempting to print the prompt.

**Comment by Kurren123** [comment]
@dpratt71 I haven't touched ghci or amended any ghci files. 

Could this be an issue with intero or whatever package is used to get the type hovers? Wonder how I can find out

**Comment by martrik** [comment]
@Kurren123 Haskelly doesn't support files or Stack projects which have a path with white spaces. This is due to Intero not escaping white spaces. Sorry for the inconvenience.

**Comment by martrik** [comment]
Actually, there's one issue already created for this #14 . So I'm closing this.
