### ISSUE TITLE
GHCi is not being passed the :load command

### ISSUE THREAD

**Issue by smobs** [haskelly-dev/Haskelly#20]
Using the `Load GHCi` button has the following effect on my Windows machine (v 4.10)

1) Runs `cd C:\myproject\src\`
2) Runs `stack ghci`
3) Waits until the user exits GHCi
4) Runs `:load MyModule` which is not recognised as a command.

I don't know enough about vscode extensions to pass the command in, but I think you could change the command that you use to `stack ghci --ghci-options MyModule.hs`

**Comment by martrik** [comment]
We've just released a new version (0.4.11) which contains a bug fix for path white spaces normalisation. I'm not sure if it might be related to this issue, could you tell us if you are still experiencing it with the update? Thanks!

**Comment by louy2** [comment]
I am reproducing this problem on Win 10, with VS Code 1.9.1 and latest Haskelly.

**Comment by martrik** [comment]
Could you please send me a picture (or even better a gif) of what happens in the VS Code terminal when you click "Load GHCi"? Thanks a lot!

**Comment by smobs** [comment]
I updated to the latest Haskelly and this is the screenshot:

![image](https://cloud.githubusercontent.com/assets/3480534/22876017/77395e8c-f1c6-11e6-9c00-c722f214d844.png)

**Comment by martrik** [comment]
We've released version 0.4.15 with the fix that you suggested. Let us know if the issue has been solved.

**Comment by smobs** [comment]
Works great, thanks!
