### ISSUE TITLE
unclear install instructions

### ISSUE THREAD

**Issue by rvion** [haskelly-dev/Haskelly#25]
I think the https://github.com/haskelly-dev/Haskelly#requirements section is a bit lost in the readme, and I feel the readme could be vastly simplified

**Comment by martrik** [comment]
Thanks for your feedback! If you have any ideas on how to improve it, feel free to issue a pull request. We'll be glad to accept it! :)

**Comment by rvion** [comment]
here is a PR
you can check the final version here : https://github.com/rvion/Haskelly/tree/readme-enhancement#readme

**Comment by rvion** [comment]
just pushed a few tweaks.

**Comment by rvion** [comment]
pushed more fixes / simplification
