### ISSUE TITLE
how about sharing work with haskero ?

### ISSUE THREAD

**Issue by rvion** [haskelly-dev/Haskelly#31]
https://gitlab.com/vannnns/haskero seems to be an other active VSCode haskell plugin.
it seems to work quite well as of now.

/cc @ndmitchell (because I just noticed you forked this repo)

**Comment by martrik** [comment]
Hey! This is a project that we're doing at university (UCL). Because of that, we are supposed to work as independently as possible. When the course finishes ww'll consider joining forces with the Haskero developer for sure!

**Comment by rvion** [comment]
> we are supposed to work as independently as possible 
Oh, I didn't know!

How about adding a small line about that at the top of your readme ?
maybe with a link to the msdn article :)

**Comment by martrik** [comment]
That's actually a pretty good idea. We'll do that!

**Comment by ndmitchell** [comment]
How much longer does your University project last for?

I imagine this project comprises of the code, and a writeup, and you get most of the marks for the writeup? Any scope for asking if you can properly participate as an open-source project right now anyway? That seems a more accurate real-world project, although I appreciate universities are sometimes a little more protective.

**Comment by jpotecki** [comment]
Hi, participation is welcomed. We are allowed to accept pull requests

**Comment by martrik** [comment]
And the project will last until April :)
