### ISSUE TITLE
Hindent and auto-indent

### ISSUE THREAD

**Issue by rvion** [haskelly-dev/Haskelly#32]
Hindent is quite robust these days

it would be great to integrate `hindent-format`
  [marketplace link](https://marketplace.visualstudio.com/items?itemName=monofon.hindent-format)
  [github link](https://github.com/monofon/hindent-format/blob/master/src/extension.ts)

or just depends on it so it is installed automatically when one installs haskelly.

Then, the readme could advice users to add :

![image](https://cloud.githubusercontent.com/assets/2150990/22978150/d52f1b22-f391-11e6-9cdd-8f55919e3adc.png)

if they want auto indentation

**Comment by rvion** [comment]
here are a few [hindent examples](https://github.com/chrisdone/hindent/blob/master/TESTS.md)

**Comment by martrik** [comment]
We'll look into it, thanks!
