### ISSUE TITLE
goto definition + Find all references

### ISSUE THREAD

**Issue by rvion** [haskelly-dev/Haskelly#33]
`Haskero` integrates correctly with `VSCode` regarding goto definitions

pressing `F12` will go to the definition of the simbol below the cursor
pressing `shift-F12` will open the `Find all references` widget that allows to both see the definition and to see its usage across the project.

there is few code to write, vscode does most of the work.

![image](https://cloud.githubusercontent.com/assets/2150990/22978350/b19dd01c-f392-11e6-865d-a04bd34fb4f4.png)

I find this widget very usefull in other languages, it would be great for haskelly to suport it

**Comment by martrik** [comment]
That's actually something we had been thinking for the past few days. I've added it into the roadmap for future releases :)

**Comment by ryu1kn** [comment]
Hello @martrik , is there anything particular stopping you to implement this?

Thanks to the existing components you've already provided, I could get the jump to definition functionality working on my local. But like type information tooltip, jump works if the definition is in user project but doesn't if they're in the libraries (standard or 3rd-party). If it's fine, I can submit a PR. Even the jump is limited to within my project, I find it useful.

**Comment by martrik** [comment]
Hi @ryu1kn, we would greatly appreciate your PR. From there we can see how to make it work with external dependencies. Thanks!

**Comment by martrik** [comment]
Go to definition has been implemented thanks to the PR submitted by @ryu1kn I'll close this issue and open a new one to keep track of the _Find all references_ implementation.

**Comment by ryu1kn** [comment]
Thanks @martrik 👍
