### ISSUE TITLE
demo video is not available

### ISSUE THREAD

**Issue by rvion** [haskelly-dev/Haskelly#35]
when I click on the demo video link (https://www.youtube.com/watch?v=r3x64iz5xDk)
I see: 

![image](https://cloud.githubusercontent.com/assets/2150990/22979224/e362a9bc-f395-11e6-93b9-b567050914cc.png)

**Comment by rvion** [comment]
"this video is not available"
---
Impossible Operation

**Comment by martrik** [comment]
Fixed! Was set to private....
