### ISSUE TITLE
Add a Command / keybinding to get the type of the selection

### ISSUE THREAD

**Issue by rvion** [haskelly-dev/Haskelly#36]
from https://github.com/haskelly-dev/Haskelly/issues/28

> PS: @rvion There's no way of triggering type hover without a previous request coming from the IDE. Because of that we can't implement your suggestion of updating the type hover on selection change.

So could there be a key binding to ask for the type of the selection ?

- I (and others) don't use much the mouse when I code
- I (and others) often care about the type of a partially applied expression

I don't care much having to press a keybinding, but I really can't live without being able to query the type of subexpressions.

Being able to query the type of a subexpression if really usefull when you have complex and convoluted code, with heavily polymorphic code (lens, etc.). 

Type of partially applied expression will show the monomorphic restrictions imposed by the partial application, and will often help a lot understanding what are the concrete types to gives next

**Comment by martrik** [comment]
This feature has been included with the new release 0.4.29 thanks to the PR #63
