### ISSUE TITLE
Re-Use Terminal Window on Stack Run

### ISSUE THREAD

**Issue by dlorch** [haskelly-dev/Haskelly#38]
After running "Stack Run" for a couple of times, there's a growing number of terminals open. If there is already an open Stack Run terminal window, could you re-use it rather than creating a new one on each execution? Other extensions such as [Python extension](https://github.com/DonJayamanne/pythonVSCode) are doing that for example.

<img width="333" alt="bildschirmfoto 2017-02-18 um 12 17 53" src="https://cloud.githubusercontent.com/assets/43927/23092868/81bd825e-f5d4-11e6-948c-c44a5a9ebb02.png">

**Comment by jpotecki** [comment]
Actually this is an on-going discussion in the team. The reason for the current solution is that it seems to be a common practise among many other IDEs, eg. Intellij Idea, Eclipse etc

**Comment by dlorch** [comment]
I have to make an addendum to my statement above: when using the **debugger** with launch configuration ``"console": "integratedTerminal"``, the Python extension re-uses the terminal window if possible. Not sure it makes a difference, but just wanted to have it defined more precisely :-)

**Comment by martrik** [comment]
@dlorch Hi! The new version of Haskelly 0.4.23 includes a boolean configuration named: `reuseTerminal`, which if set to true will force Haskelly to just use one terminal. We hope you find this useful!

**Comment by dlorch** [comment]
@martrik Very cool, thanks!
