### ISSUE TITLE
Click on errors to jump to file/position

### ISSUE THREAD

**Issue by lylek** [haskelly-dev/Haskelly#39]
In Emacs if you run a compiler in a shell window, any errors in the standard format of filename:line_no:col_no will automatically turn into links that you can click on (or use a key combo if they're under the cursor) to take you to that file and position. It works for any language as long as they use that standard format.

That would be very helpful here in debugging Haskell code. For both compilation and runtime exceptions, you get an error in that form, e.g. "src/Lib.hs:6:36". It would be great if I could click on that to open that file with the cursor at that position.

**Comment by martrik** [comment]
This will be taken into account when we implement #29
