### ISSUE TITLE
Getting errors in test-suite main module

### ISSUE THREAD

**Issue by moodmosaic** [haskelly-dev/Haskelly#41]
![screen shot 2017-02-26 at 4 00 40 pm](https://cloud.githubusercontent.com/assets/287532/23340343/36f2975e-fc3d-11e6-9b4b-4a16cb90ef4a.jpg)

The source code of that module (together with a stack project to build it) can be found [here](https://github.com/ploeh/dependency-rejection-samples/blob/b6044dace05104fc69ec605609eee22aaa13b58e/Haskell/Discordia.hs).

**Comment by martrik** [comment]
Sorry for the late response. Currently Haskelly only supports the main target, we'll try to address this limitation in the future.

**Comment by martrik** [comment]
This is actually a duplicate of #23 I reckon.

**Comment by moodmosaic** [comment]
Yes, it's a duplicate of #23.
