### ISSUE TITLE
stack run fail to install on windows

### ISSUE THREAD

**Issue by chantisnake** [haskelly-dev/Haskelly#45]
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for unix-2.7.2.1:
    unbuildable must match <0, but the stack configuration has no specified version

Plan construction failed.
```

it seems like `stack-run` is dependent on *nix operating system.

is there any way I can bypass this?

**Comment by martrik** [comment]
Apparently there's not (https://github.com/commercialhaskell/stack/issues/3053). We'll keep this in mind and try to implement a different solution to run the Stack project instead of `stack-run`.

**Comment by CameronAavik** [comment]
Seems this issue should be resolved with this: https://github.com/yamadapc/stack-run/issues/6

**Comment by martrik** [comment]
@CameronAavik thank you for letting us now. I'll close the issue then!
