### ISSUE TITLE
Host Stopped working

### ISSUE THREAD

**Issue by Kuroskira** [haskelly-dev/Haskelly#46]
After I installed the latest VSCode version Haskelly stated to stop working. Tried to reinstall it but still doing it. Should I reinstall VSCode?

**Comment by martrik** [comment]
I've tested Haskelly with the new VS Code and it seems to work OK. Do you keep getting that error?

**Comment by Kuroskira** [comment]
No, I found the problem with the new VSCode version, git.enabled stops all extensions, disable it to fix.

**Comment by martrik** [comment]
I guess that's been solved in a new release of VS Code so I'm closing the issue.
