### ISSUE TITLE
stack run with file-watch?

### ISSUE THREAD

**Issue by coodoo** [haskelly-dev/Haskelly#53]
Is it possible to make the `Stack Run` button run following command?

```
stack build --fast --file-watch
```

So that it keeps on watching for file changes and report errors?

**Comment by martrik** [comment]
Wouldn't that be in the `Stack Build` button? In any case, what do you think of a configuration variable that allows you to add flags to the default commands for each of the Stack buttons?

**Comment by coodoo** [comment]
Having configuration variables would be great, that was actually the first thing I looked into :)
