### ISSUE TITLE
Haskelly doesn't show autocomplete suggestions or type hover

### ISSUE THREAD

**Issue by nabeelomer** [haskelly-dev/Haskelly#55]
When I hover over something I get a "Loading..." tooltip but nothing happens after that and no autocomplete suggestions show up either.

**Comment by Genora51** [comment]
### See #17:

You need to install intero, QuickCheck and stack-run, as per [README.md](https://github.com/haskelly-dev/Haskelly/blob/master/README.md#installation):

    stack install intero QuickCheck stack-run  # for a global installation
    stack build intero QuickCheck stack-run # for a local installation

**Comment by nabeelomer** [comment]
I was under the impression that the extension is supposed to install all the required software, anyway thanks.

**Comment by martrik** [comment]
@nabeelomer Checking for dependencies and notifying the user if they are not installed is a feature in our timeline. This is a trend in popular extensions and we think it makes a lot of sense to add it in Haskelly.

**Comment by nabeelomer** [comment]
It sure does.

**Comment by rainbyte** [comment]
I have installed intero, QuickCheck and stack-run, as it is stated by Readme, but I got the "Loading..." message anyway.

This happens with last release, version 0.4.27

**Comment by martrik** [comment]
Hi @rainbyte are you still experiencing this problem? Could you please open the Developer Tools (Located in Help menu) and take a screenshot of the error?

**Comment by rainbyte** [comment]
After updating vscode to version 1.18.1, I could not reproduce the issue anymore on my pc.
Maybe it does happen only with old version of vscode?

Now it takes a while to show the types, but after that I don't get the "Loading..." msg.

**Comment by rainbyte** [comment]
stack was also updated on my pc (from version 1.5.x to 1.6.1), if that helps to explain something.
