### ISSUE TITLE
How to configure ghci?

### ISSUE THREAD

**Issue by Rhywun** [haskelly-dev/Haskelly#58]
I am fairly new to Haskell and this plug-in - trying to configure the ghci prompt when I load my file with the "Load GHCi" button. There is a line reading as follows, which varies every time I launch it:

> Loaded GHCi configuration from ...long path.../ghci-script

I'm not understanding why stack uses a different config file every time it launches... After some research I tried setting the prompt in ~/.ghc/.ghci but that didn't work for either `ghci` or `stack ghci`. I am able to set the prompt with `:set prompt ...` at the existing prompt after launching but that's not ideal :)

Is there maybe a standard location under ~/.stack for configuring ghci? I couldn't find any reference on their website.

Thanks

**Comment by martrik** [comment]
Hi! As far as I can tell the configuration for stack should be added in `.ghc/ghci.conf`. That's at least how it works for me on macOS. I'm afraid though that this is not a question directly related to the Haskelly extension, so I'll have to close the ticket.
