### ISSUE TITLE
When Haskelly extension loads, the bottom taskbar shows "Load GHCi, Run File, ..." multiple times

### ISSUE THREAD

**Issue by zbs** [haskelly-dev/Haskelly#60]
- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
language-haskell|jus|2.4.0
python|ms-|0.8.0
haskelly|UCL|0.4.27

![vscodesnapshot](https://user-images.githubusercontent.com/1444551/33234366-c7295c86-d1f3-11e7-8524-b2fe3682cc1d.PNG)

**Comment by martrik** [comment]
Hello! This is certainly a weird bug. Does it show after opening the first Haskell file or after multiple?Also, if you don't want to see the buttons at all you can disable them in the configuration.

**Comment by rodrigoelp** [comment]
Is this still a thing? I am using insiders and I can't see it in mine.

**Comment by martrik** [comment]
We'll close this issue for now as it seems not to exist anymore.
