### ISSUE TITLE
Implement Find all references

### ISSUE THREAD

**Issue by martrik** [haskelly-dev/Haskelly#62]

**Comment by ryu1kn** [comment]
Intero provides a command `:uses` that "find uses of an identifier in **a module**."

https://github.com/commercialhaskell/intero/blob/master/TOOLING.md

When I executed `:uses` on the use of `a` in A.hs, it gave me the locations of `a`s in both A.hs and B.hs. But when I did it in B.hs, it only gave `a`'s location in B.hs. So not enough to use it for a "find usages/references" feature 😞 

```
-- A.hs
foo = a

-- B.hs
a = ...
```

**Comment by martrik** [comment]
Hi @ryu1kn thank you for pointing that out. I think that despite this limitation it might be worth giving it a try, as it is probably the only feasible way of implementing the "find al references". Are you planing on working on this? We are not actively adding new features to Haskelly so it might take a while.

**Comment by ryu1kn** [comment]
Sure, as I've already had a look at this a bit, I believe I know where to change 😉

**Comment by martrik** [comment]
That's awesome. Looking forward to your PR!

**Comment by martrik** [comment]
Thanks to @ryu1kn and his PR (#64) we can now close this PR. The feature has been included in version `0.5.0`.
