### ISSUE TITLE
Haskelly causes typescript server in VSCode to crash

### ISSUE THREAD

**Issue by zor-el** [haskelly-dev/Haskelly#66]
Please see Microsoft/vscode#40849

**Comment by martrik** [comment]
Hello @zor-el. Sorry for the late reply. Is this still an issue?

**Comment by zor-el** [comment]
Well, since I disabled the extension, I couldn't tell. But my guess is it must be, given there've been no updates for this add-on since. :-)

I just enabled it again and there were no immediate issues. That is no proof though, since the issues never happened immediately, but sporadically. The best I can do is to leave it on and report back if something happens.

**Comment by zor-el** [comment]
Hi @martrik, I can happily report that the aforementioned issue has not manifested in the 21 days since my last comment. I haven't used VSCode *that* much in that time, but often enough to feel confident to say the issue seems to have evaporated. Thanks for whatever you did to make it happen.

**Comment by martrik** [comment]
Hello! That's nice to hear, I'll close this issue for now then. Thanks!
