### ISSUE TITLE
Having version 0.4.29, no update to 0.5.0 offered

### ISSUE THREAD

**Issue by stefanscheidt** [haskelly-dev/Haskelly#69]
The latest release of Haskelly seems to be 0.5.0.
In VS Code, the extension has the version number 0.4.29 (where the latest 0.4.x seems to be 0.4.27), and no update is offered.

I use 1.19.2 on macOS High Sierra 10.13.3.

**Comment by mindbound** [comment]
Same on VS Code 1.20.1, Arch Linux 4.15.5 x64.

**Comment by martrik** [comment]
I'm afraid that we can't really do anything about this. It might be that VS Code servers are a bit slow propagating new versions. I'll close this issue hoping the problem has been solved already.
