### ISSUE TITLE
Prelude function highlighting

### ISSUE THREAD

**Issue by willbasky** [haskelly-dev/Haskelly#73]
![haskelly](https://user-images.githubusercontent.com/28530747/38579465-8dde204a-3d20-11e8-83b0-bc73d5492da2.jpg)
There is prelude function highlighting in demo how haskelly works. `Map` and `show`. 
I can`t find how it is possible. Can somebody explain?

**Comment by martrik** [comment]
Hello @willbasky. This feature comes from the Haskell Syntax Highlight package which is automatically installed when you install Haskelly. If that wasn't the case you can manually do so in the Extensions menu of VS Code.

**Comment by willbasky** [comment]
Haskell Syntax Highlight was installed. But i didn`t see any prelude function highlighting.

**Comment by martrik** [comment]
I'm sorry to hear that. I encourage you to open an issue in their repo if you are still experiencing this problem. I'll close this issue as it isn't concerned with Haskelly directly.
