### ISSUE TITLE
Cannot install stack-run with newer GHC etc

### ISSUE THREAD

**Issue by mrkafk** [haskelly-dev/Haskelly#84]
The page https://marketplace.visualstudio.com/items?itemName=UCL.haskelly explicitly requires installing `stack-run`. However, it seems that `stack-run` is not actively maintained anymore:

https://stackoverflow.com/a/52573173/2022518

I managed to install `stack-run` but only by going back in time so to speak:

```
% cat stack.yaml 
packages:
- .
resolver: lts-9.21
```

Do I really need `stack-run` for this extension to work properly? If I do, why is it still a dependency?

**Comment by deklanw** [comment]
https://github.com/yamadapc/stack-run/issues/17
