### ISSUE TITLE
Stop depending on stack-run

### ISSUE THREAD

**Issue by shiyuge** [haskelly-dev/Haskelly#88]
It seems that `stack-run` is not being actively maintained, last commit being May 12, 2017.

While trying to install `stack-run`, an error shows up indicating that it's dependency chain has broken:
```
In the dependencies for stack-run-0.1.1.4:
    conduit-extra-1.2.3.2 from stack configuration does not match >=1.1 && <1.2 (latest matching
                          version is 1.1.17)
needed since stack-run is a build target.
```
Do we really need to depend on this package?

**Comment by martrik** [comment]
Hello @shiyuge! It's a way to easily run a Stack project. We aren't actively maintaining Haskelly either, but we do accept PRs and release them. So if you have any suggestion that might be able to substitute `stack-run`, please feel free to contribute :)

**Comment by Atry** [comment]
I think recent version of `stack` has a built-in `stack run` sub-command.
